stages:
  - build
  - test

compile:
  stage: build
  image: golang:latest
  script:
    - go get
    - go vet
    - go build
  artifacts:
    paths:
      - gitlab-codeowners

build-image:
  stage: build
  needs:
    - compile
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:latest"

simple-test:
  stage: test
  image: alpine:latest
  script:
    - ./gitlab-codeowners
