include:
  - project: "${CI_PROJECT_PATH}"
    ref: "${CI_COMMIT_SHA}"
    file: templates/validate-codeowners.yml
    inputs:
      GITLAB_TOKEN: ${GITLAB_TOKEN}

compile:
  stage: build
  image: golang:latest
  script:
    - go get
    - go vet
    - CGO_ENABLED=0 go build
  artifacts:
    paths:
      - gitlab-codeowners
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Dockerfile
        - "**/*.go"

build-image:
  stage: build
  needs:
    - compile
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Dockerfile
        - "**/*.go"

test-valid-codeowners:
  extends: .validate-codeowners

.test-failure:
  extends: .validate-codeowners
  script:
    - |
      echo Disable error checking before running failure test
      set +e
    - /gitlab/gitlab-codeowners | tee $CI_JOB_NAME.test
    - |
      echo Re-enable error checking
      set -e

test-bad-syntax:
  extends: .test-failure
  script:
    # Remove ./CODEOWNERS so that it validates ./docs/CODEOWNERS
    - rm ./CODEOWNERS
    - !reference [.test-failure, script]
    - diff $CI_JOB_NAME.test tests/CODEOWNERS.bad-syntax.test

test-bad-owner-patterns:
  extends: .test-failure
  script:
    - cp tests/CODEOWNERS.bad-owners ./CODEOWNERS
    - !reference [.test-failure, script]
    - diff $CI_JOB_NAME.test tests/CODEOWNERS.bad-owners.test

test-bad-filepath-patterns:
  extends: .test-failure
  script:
    - cp tests/CODEOWNERS.bad-paths ./CODEOWNERS
    - !reference [.test-failure, script]
    - diff $CI_JOB_NAME.test tests/CODEOWNERS.bad-paths.test
