stages:
  - build
  - test

compile:
  stage: build
  image: golang:latest
  script:
    - go get
    - go vet
    - CGO_ENABLED=0 go build
  artifacts:
    paths:
      - gitlab-codeowners
  rules:
    # Make this job optional for manual pipeline runs from the web UI
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
    # Otherwise, run this job whenever the Dockerfile or *.go files in main change
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Dockerfile
        - "**/*.go"

build-image:
  stage: build
  needs:
    - compile
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    # Make this job optional for manual pipeline runs from the web UI
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
    # Otherwise, run this job whenever the Dockerfile or *.go files in main change
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Dockerfile
        - "**/*.go"

simple-test:
  stage: test
  image: registry.gitlab.com/tedspinks/gitlab-codeowners:latest
  variables:
    DEBUG: "false"
  script:
    - pwd
    - ls -l /
    - ls -l /gitlab
    - /gitlab/gitlab-codeowners
